---
name: Generate and publish core docs

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Generate and publish core docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish docs
        uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          working-directory: bongocore
          github_token: ${{ secrets.GITHUB_TOKEN }}
