---
name: Lint Go code

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint Go code
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: bongocli
          args: --config=.golangci.yml
