---
name: Release code to master branch

on:
  workflow_dispatch:

jobs:
  build:
    name: Release code to master branch
    runs-on: ubuntu-latest

    steps:
      - name: Merge branch to master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: master
          GITHUB_TOKEN: ${{ bongodb.KEY }}

      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
